[package]
name = "buffi_example"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
buffi_macro = { path = "../../buffi_macro" }
bincode = "1.3.3"
serde = { version = "1.0.214", features = ["derive"] }
tokio = { version = "1.41.1", features = ["rt-multi-thread"] }